// import { useDispatch, useSelector } from "react-redux"
import { MiddleBlock, RightBlock, RightSection } from "../../styles/containers/containers.styles"

const Home = () => {
    // const logoutReducerData = useSelector(reducers => reducers.loginReducer)
    // const dispatch = useDispatch()

    return (
        <>
            <RightSection>
                <MiddleBlock>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                    <h3>Middle</h3>
                </MiddleBlock>
                <RightBlock>
                    <h3>Right</h3>
                    <h3>Right</h3>
                    <h3>Right</h3>
                    <h3>Right</h3>
                    <h3>Right</h3>
                    <h3>Right</h3>
                    <h3>Right</h3>
                    <h3>Right</h3>
                    <h3>Right</h3>
                    <h3>Right</h3>
                    <h3>Right</h3>
                    <h3>Right</h3>
                    <h3>Right</h3>
                    <h3>Right</h3>
                </RightBlock>
            </RightSection>
        </>
    )
}

export default Home