export const INITIATE_ADD_QUESTION = "INITIATE_ADD_QUESTION"
export const ADD_QUESTION_SUCCESS = "ADD_QUESTION_SUCCESS"
export const ADD_QUESTION_ERROR = "ADD_QUESTION_ERROR"
export const ADD_QUESTION_RESET = "ADD_QUESTION_RESET"

export const INITIATE_GET_PUBLIC_QUESTIONS = "INITIATE_GET_PUBLIC_QUESTIONS"
export const GET_PUBLIC_QUESTIONS_SUCCESS = "GET_PUBLIC_QUESTIONS_SUCCESS"
export const GET_PUBLIC_QUESTIONS_ERROR = "GET_PUBLIC_QUESTIONS_ERROR"

export const INITIATE_LOGIN = "INITIATE_LOGIN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"


export const INITIATE_REGISTRATION = "INITIATE_REGISTRATION"
export const REGISTRATION_SUCCESS = "REGISTERATION_SUCCESS"
export const REGISTRATION_ERROR = "REGISTRATION_ERROR"


export const INITIATE_LOGOUT = "INITIATE_LOGOUT"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_ERROR = "LOGOUT_ERROR"

export const INITIATE_VERIFY_EMAIL = "INITIATE_VERIFY_EMAIL"
export const VERIFY_EMAIL_SUCCESS = "VERIFY_EMAIL_SUCCESS"
export const VERIFY_EMAIL_ERROR = "VERIFY_EMAIL_ERROR"

export const INITIATE_SEND_RESET_PASSWORD_EMAIL = "INITIATE_SEND_RESET_PASSWORD_EMAIL"
export const SEND_RESET_PASSWORD_EMAIL_SUCCESS = "SEND_RESET_PASSWORD_EMAIL_SUCCESS"
export const SEND_RESET_PASSWORD_EMAIL_ERROR = "SEND_RESET_PASSWORD_EMAIL_ERROR"


export const INITIATE_VERIFY_RESET_PASSWORD = "INITIATE_VERIFY_RESET_PASSWORD"
export const VERIFY_RESET_PASSWORD_SUCCESS = "VERIFY_RESET_PASSWORD_SUCCESS"
export const VERIFY_RESET_PASSWORD_ERROR = "VERIFY_RESET_PASSWORD_ERROR"