export const INITIATE_LOGIN = "INITIATE_LOGIN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"


export const INITIATE_REGISTRATION = "INITIATE_REGISTRATION"
export const REGISTERATION_SUCCESS = "REGISTERATION_SUCCESS"
export const REGISTRATION_ERROR = "REGISTRATION_ERROR"